### ISSUE TITLE
What is Phone audio on the diagram?

### ISSUE THREAD

**Issue by sergiovillaverde** [roncapat/Ford-Fiesta-MK5-MS-CAN-bus#1]
Hi there!
I'm trying to use the mic that my Fiesta has onto a Android screen that i bought.
I understand that "Phone audio +" and "Phone audio -" are the pins from that mic right?

**Comment by roncapat** [comment]
@sergiovillaverde I think so, but I don't have my Fiesta anymore so I'm not able to test it for you. Nevertheless, if you solder a 3,5 mm jack you may try with a cheap USB audio interface and a laptop to record sounds first.
Before doing anything, use a multimeter to check if no strange voltages appear on those two pins.

**Comment by sergiovillaverde** [comment]
Oh nice, thanks for the idea!
I'll try these next days and i'll let you know what i find.
